// Car form field configuration
export const carFormFields = [
  {
    name: "brand",
    label: "What is your vehicle Brand?",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Toyota, Honda, Suzuki",
    required: true,
    minLength: 2,
    maxLength: 30,
  },
  {
    name: "city",
    label: "What is your city?",
    type: "select" as const,
    placeholder: "--- Select Your City ---",
    required: true,
    options: [
      { value: "karachi", label: "Karachi" },
      { value: "lahore", label: "Lahore" },
      { value: "islamabad", label: "Islamabad" },
      { value: "rawalpindi", label: "Rawalpindi" },
      { value: "faisalabad", label: "Faisalabad" },
      { value: "multan", label: "Multan" },
      { value: "peshawar", label: "Peshawar" },
      { value: "quetta", label: "Quetta" },
    ],
  },
  {
    name: "purchaseDate",
    label: "What is your car Purchase date & year?",
    type: "date" as const,
    placeholder: "DD/MM/YYYY",
    required: true,
  },
  {
    name: "model",
    label: "What is your car model year?",
    type: "select" as const,
    placeholder: "--- Select Model Year ---",
    required: true,
    options: [
      { value: "2025", label: "2025" },
      { value: "2024", label: "2024" },
      { value: "2023", label: "2023" },
      { value: "2022", label: "2022" },
      { value: "2021", label: "2021" },
      { value: "2020", label: "2020" },
      { value: "2019", label: "2019" },
      { value: "older", label: "2018 & Older" },
    ],
  },
  {
    name: "currentValue",
    label: "What is your car Current Value? (PKR)",
    type: "input" as const,
    inputType: "number" as const,
    placeholder: "e.g. 2500000",
    required: true,
    minValue: 300000,
    maxValue: 100000000,
  },
];

// bikeFormFields.ts

export const bikeFormFields = [
  {
    name: "brand",
    label: "What is your vehicle Brand?",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Honda, Yamaha, Suzuki",
    required: true,
    minLength: 2,
    maxLength: 30,
  },
  {
    name: "bikeCC",
    label: "What is your Bike CC?",
    type: "select" as const,
    placeholder: "--- Select Bike CC ---",
    required: true,
    options: [
      { value: "70cc", label: "70 CC" },
      { value: "100cc", label: "100 CC" },
      { value: "125cc", label: "125 CC" },
      { value: "150cc", label: "150 CC" },
      { value: "200cc", label: "200 CC" },
      { value: "250cc", label: "250 CC" },
      { value: "above250", label: "Above 250 CC" },
    ],
  },
  {
    name: "purchaseDate",
    label: "What is your bike Purchase date & year?",
    type: "date" as const,
    placeholder: "DD/MM/YYYY",
    required: true,
  },
  {
    name: "model",
    label: "What is your bike model year?",
    type: "select" as const,
    placeholder: "--- Select Model Year ---",
    required: true,
    options: [
      { value: "2025", label: "2025" },
      { value: "2024", label: "2024" },
      { value: "2023", label: "2023" },
      { value: "2022", label: "2022" },
      { value: "2021", label: "2021" },
      { value: "2020", label: "2020" },
      { value: "2019", label: "2019" },
      { value: "older", label: "2018 & Older" },
    ],
  },
  {
    name: "currentValue",
    label: "What is your bike Current Value? (PKR)",
    type: "input" as const,
    inputType: "number" as const,
    placeholder: "e.g. 150000",
    required: true,
    minValue: 30000,    
    maxValue: 5000000,  
  },
];

// Health Takaful form field configuration
export const healthTakafulFormFields = [
  {
    name: "yourName",
    type: "input" as const,
    placeholder: "Your Name",
    required: true,
  },
  {
    name: "companyName",
    type: "input" as const,
    placeholder: "Company Name",
    required: true,
  },
  {
    name: "workEmail",
    type: "input" as const,
    placeholder: "Work email",
    required: true,
  },
  {
    name: "city",
    type: "select" as const,
    placeholder: "City",
    required: true,
    options: [
      { value: "karachi", label: "Karachi" },
      { value: "lahore", label: "Lahore" },
      { value: "islamabad", label: "Islamabad" },
      { value: "rawalpindi", label: "Rawalpindi" },
    ],
  },
  {
    name: "employeeCount",
    type: "select" as const,
    placeholder: "Number of employees",
    required: true,
    options: [
      { value: "1-10", label: "1-10" },
      { value: "11-50", label: "11-50" },
      { value: "51-100", label: "51-100" },
      { value: "100+", label: "100+" },
    ],
  },
  {
    name: "insured",
    type: "select" as const,
    placeholder: "Are you insured",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];
// Fire Takaful form field configuration
export const fireTakafulFormFields = [
  {
    name: "yourName",
    type: "input" as const,
    placeholder: "Your Name",
    required: true,
  },
  {
    name: "companyName",
    type: "input" as const,
    placeholder: "Company Name",
    required: true,
  },
  {
    name: "workEmail",
    type: "input" as const,
    placeholder: "Work email",
    required: true,
  },
  {
    name: "city",
    type: "select" as const,
    placeholder: "City",
    required: true,
    options: [
      { value: "karachi", label: "Karachi" },
      { value: "lahore", label: "Lahore" },
      { value: "islamabad", label: "Islamabad" },
      { value: "rawalpindi", label: "Rawalpindi" },
    ],
  },
  {
    name: "employeeCount",
    type: "select" as const,
    placeholder: "Number of employees",
    required: true,
    options: [
      { value: "1-10", label: "1-10" },
      { value: "11-50", label: "11-50" },
      { value: "51-100", label: "51-100" },
      { value: "100+", label: "100+" },
    ],
  },
  {
    name: "insured",
    type: "select" as const,
    placeholder: "Are you insured",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];
