// Car form field configuration
export const carFormFields = [
  {
    name: "name",
    label: "Your Full Name",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Ahmad Khan",
    required: true,
    minLength: 2,
    maxLength: 50,
  },
  {
    name: "phoneNumber",
    label: "Your Phone Number",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. 3001234567",
    required: true,
    minLength: 10,
    maxLength: 15,
  },
  {
    name: "brand",
    label: "What is your vehicle Brand?",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Toyota, Honda, Suzuki",
    required: true,
    minLength: 2,
    maxLength: 30,
  },


  {
    name: "model",
    label: "Car Manufacturing Year (Model Year)?",
    type: "select" as const,
    placeholder: "--- Select Model Year ---",
    required: true,
   options: [
  { value: "2025", label: "2025" },
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003"  },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
  { value: "older", label: "1999 & Older" }, 
],
  },
  {
    name: "currentValue",
    label: "What is your car Current Value? (PKR)",
    type: "input" as const,
    inputType: "number" as const,
    placeholder: "e.g. 2500000",
    required: true,
    minValue: 300000,
    maxValue: 100000000,
  },

 
  {
    name: "trackerAvailable",
    label: "Is Tracker Required? (RS 15000)",
    type: "select" as const,
    placeholder: "--- Select ---",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];

// bikeFormFields.ts

export const bikeFormFields = [
   {
    name: "name",
    label: "Your Full Name",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Ahmad Khan",
    required: true,
    minLength: 2,
    maxLength: 50,
  },
  {
    name: "phoneNumber",
    label: "Your Phone Number",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. 3001234567",
    required: true,
    minLength: 10,
    maxLength: 15,
  },
  {
    name: "brand",
    label: "What is your vehicle Brand?",
    type: "input" as const,
    inputType: "text" as const,
    placeholder: "e.g. Honda, Yamaha, Suzuki",
    required: true,
    minLength: 2,
    maxLength: 30,
  },
  {
    name: "bikeCC",
    label: "What is your Bike CC?",
    type: "select" as const,
    placeholder: "--- Select Bike CC ---",
    required: true,
    options: [
      { value: "70cc", label: "70 CC" },
      { value: "100cc", label: "100 CC" },
      { value: "125cc", label: "125 CC" },
      { value: "150cc", label: "150 CC" },
      { value: "200cc", label: "200 CC" },
      { value: "250cc", label: "250 CC" },
      { value: "above250", label: "Above 250 CC" },
    ],
  },

  {
    name: "model",
    label: "What is your bike model year?",
    type: "select" as const,
    placeholder: "--- Select Model Year ---",
    required: true,
   options: [
  { value: "2025", label: "2025" },
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003"  },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
  { value: "older", label: "1999 & Older" }, 
],
  },
  {
    name: "currentValue",
    label: "What is your bike Current Value? (PKR)",
    type: "input" as const,
    inputType: "number" as const,
    placeholder: "e.g. 150000",
    required: true,
    minValue: 30000,    
    maxValue: 5000000,  
  },
   {
    name: "trackerAvailable",
    label: "Is Tracker Required? (RS 15000)",
    type: "select" as const,
    placeholder: "--- Select ---",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];

// Health Takaful form field configuration
export const healthTakafulFormFields = [
  {
    name: "yourName",
    type: "input" as const,
    placeholder: "Your Name",
    required: true,
  },
  {
    name: "companyName",
    type: "input" as const,
    placeholder: "Company Name",
    required: true,
  },
  {
    name: "workEmail",
    type: "input" as const,
    placeholder: "Work email",
    required: true,
  },
  {
    name: "city",
    type: "select" as const,
    placeholder: "City",
    required: true,
    options: [
      { value: "karachi", label: "Karachi" },
      { value: "lahore", label: "Lahore" },
      { value: "islamabad", label: "Islamabad" },
      { value: "rawalpindi", label: "Rawalpindi" },
    ],
  },
  {
    name: "employeeCount",
    type: "select" as const,
    placeholder: "Number of employees",
    required: true,
    options: [
      { value: "1-10", label: "1-10" },
      { value: "11-50", label: "11-50" },
      { value: "51-100", label: "51-100" },
      { value: "100+", label: "100+" },
    ],
  },
  {
    name: "insured",
    type: "select" as const,
    placeholder: "Are you insured",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];
// Fire Takaful form field configuration
export const fireTakafulFormFields = [
  {
    name: "yourName",
    type: "input" as const,
    placeholder: "Your Name",
    required: true,
  },
  {
    name: "companyName",
    type: "input" as const,
    placeholder: "Company Name",
    required: true,
  },
  {
    name: "workEmail",
    type: "input" as const,
    placeholder: "Work email",
    required: true,
  },
  {
    name: "city",
    type: "select" as const,
    placeholder: "City",
    required: true,
    options: [
      { value: "karachi", label: "Karachi" },
      { value: "lahore", label: "Lahore" },
      { value: "islamabad", label: "Islamabad" },
      { value: "rawalpindi", label: "Rawalpindi" },
    ],
  },
  {
    name: "employeeCount",
    type: "select" as const,
    placeholder: "Number of employees",
    required: true,
    options: [
      { value: "1-10", label: "1-10" },
      { value: "11-50", label: "11-50" },
      { value: "51-100", label: "51-100" },
      { value: "100+", label: "100+" },
    ],
  },
  {
    name: "insured",
    type: "select" as const,
    placeholder: "Are you insured",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
];
